version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Running tests
      - npm test
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 569339242131.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t code-deply-node .
      - docker tag code-deply-node:latest 569339242131.dkr.ecr.us-east-1.amazonaws.com/code-deply-node:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push 569339242131.dkr.ecr.us-east-1.amazonaws.com/code-deply-node:latest
      - printf '[{"name":"code-deply-node","imageUri":"569339242131.dkr.ecr.us-east-1.amazonaws.com/code-deply-node:latest"}]' > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json


